<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TestNG_vfb-20</name>
   <tag></tag>
   <elementGuidId>bb106d05-6575-445b-ae16-53b5aee31a3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vfb-20-3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vfb-20-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>357f8516-d2c0-4337-aaa9-61eaa1af0847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0f49dad7-80e8-4cc6-b74a-f4a90245c21e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vfb-20[]</value>
      <webElementGuid>50207401-191a-46a2-859b-3846afba2bf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vfb-20-3</value>
      <webElementGuid>101d99c3-4bc0-43c6-8e36-f68125e5ad30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Core Java</value>
      <webElementGuid>3ffad25f-b6a7-426d-b316-3a218c1ebbd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vfb-checkbox  </value>
      <webElementGuid>1cb45601-0edc-4fe6-9c15-dbc3565079fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vfb-20-3&quot;)</value>
      <webElementGuid>82d029ff-103f-4134-8ac4-99ab646d24ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vfb-20-3']</value>
      <webElementGuid>daeab29b-6a35-4cbc-baea-3e78f7f0ae69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='item-vfb-20']/div/span[4]/input</value>
      <webElementGuid>6153be0e-2306-49ab-a504-59dc1c05bd5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[9]/div/span[4]/input</value>
      <webElementGuid>d0773bab-c0c5-4bda-ab44-beacbc3bb9d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'vfb-20[]' and @id = 'vfb-20-3']</value>
      <webElementGuid>7702048c-670b-4c66-8545-0703bfb09c7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
