<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Street Address_vfb-13address-2</name>
   <tag></tag>
   <elementGuidId>3ff38bf6-b744-4ddf-ab3a-962d74089d55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vfb-13-address-2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vfb-13-address-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7c9eeae2-fec9-49e7-8df9-6c8e269a4bb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dd2b8d35-4459-4665-b286-a8c5ee6db98b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vfb-13[address-2]</value>
      <webElementGuid>9a5cd9ae-f7b2-40cc-ae47-b751b3402a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vfb-13-address-2</value>
      <webElementGuid>cdcbd568-366a-40af-804f-a352b98be599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>ddc54b87-fbca-49a3-8afa-9f5b3fbd444f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vfb-text vfb-medium  </value>
      <webElementGuid>aea80d95-b1e5-45c7-a782-6d018862b822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vfb-13-address-2&quot;)</value>
      <webElementGuid>b4f07436-5ca7-43bd-8f0e-a60e0a7b3146</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vfb-13-address-2']</value>
      <webElementGuid>bac59294-a916-4d39-b6e2-4c81db7f80e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='item-vfb-13']/div/span[2]/input</value>
      <webElementGuid>3bdf56cf-b613-40d8-b6dc-aa55ef660eeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/span[2]/input</value>
      <webElementGuid>6211af84-9361-442b-af0f-18545730e94d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'vfb-13[address-2]' and @id = 'vfb-13-address-2']</value>
      <webElementGuid>54ae5010-8a01-4367-ae65-15edbeb9e83e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
