<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_City_vfb-13state</name>
   <tag></tag>
   <elementGuidId>4b73d100-2359-46c5-98a2-b294c9179c94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vfb-13-state']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vfb-13-state</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a1bda8a3-2257-4de2-a41b-75d8ee88566c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0d15c6d0-cf85-40a5-b15a-7b3b3d82d3f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vfb-13[state]</value>
      <webElementGuid>ad907bd1-23eb-4b80-832f-70f1a25cf483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vfb-13-state</value>
      <webElementGuid>fde9beb9-826c-4b7f-b797-8a32ba64b008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>9bdaceb1-13ac-44b9-833e-c7de92a653b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vfb-text vfb-medium  </value>
      <webElementGuid>2ac437b3-0450-44b8-812d-b9b620b18af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vfb-13-state&quot;)</value>
      <webElementGuid>e18774ab-24d6-4329-98be-3b0b22ff04ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vfb-13-state']</value>
      <webElementGuid>e605fd2d-5f5e-4e9a-8e91-3e46186cf76a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='item-vfb-13']/div/span[4]/input</value>
      <webElementGuid>f7a761ec-b3b2-48d2-a723-0e1116276789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[4]/input</value>
      <webElementGuid>a1c2f972-1d89-4d79-a0e7-e9cff1977e8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'vfb-13[state]' and @id = 'vfb-13-state']</value>
      <webElementGuid>7530cf53-9827-483b-906f-0ebb425b8cbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
